name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci
      - run: npm run dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/pack/Markdown-Studio-*-Setup-*.exe
            out/pack/Markdown-Studio-*-Portable-*.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
